name: Update Profile Views Badge

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch: # Allow manual trigger

jobs:
  update-views:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Repository Traffic Data
        run: |
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GH_VIEWS }}" \
            https://api.github.com/repos/hxnain619/hxnain619/traffic/views)

          echo "API Response: $RESPONSE"

          TOTAL_VIEWS=$(echo $RESPONSE | jq '.count // 0')

          echo "Total Views: $TOTAL_VIEWS"
          if [ "$TOTAL_VIEWS" == "null" ]; then
            TOTAL_VIEWS=0
          fi
          echo "TOTAL_VIEWS=$TOTAL_VIEWS" >> $GITHUB_ENV

      - name: Update Badge JSON
        run: |
          jq --arg views "$TOTAL_VIEWS" \
            '.message = ($views // "0") | .color = "#951F44"' profile-views.json > temp.json && mv temp.json profile-views.json

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name 'GitHub Actions'
          git config --local user.email 'actions@github.com'
          git add profile-views.json
          git diff --cached --exit-code || git commit -m "Update Profile Views Badge: $TOTAL_VIEWS views"
          git push || echo "No changes to push"
