name: Update Profile Views

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Trigger manually as well

jobs:
  update-views:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Profile Data from GitHub
        run: |
          # Get the number of followers (or profile views) from the GitHub API
          PROFILE_VIEWS=$(curl -s https://api.github.com/users/hxnain619 | jq .followers)

          # Generate the dynamic badge URL
          badge_url="https://img.shields.io/badge/Profile%20views-${PROFILE_VIEWS}-blue?style=for-the-badge"
          echo "Dynamic Badge URL: $badge_url"

          # Replace the placeholder {{ dynamic_count }} in README.md with the actual value
          sed -i "s/{{ dynamic_count }}/$PROFILE_VIEWS/g" README.md

          # Commit the changes to README.md with updated views count
          git config --local user.name 'GitHub Actions'
          git config --local user.email 'actions@github.com'
          git add README.md
          git commit -m "Update profile views to $PROFILE_VIEWS"
          git push
