name: Update Profile Views

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Trigger manually as well

jobs:
  update-views:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grants write access to the repository content
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch Profile Data from GitHub
        run: |
          PROFILE_VIEWS=$(curl -s https://api.github.com/users/hxnain619 | jq .followers)
          echo "PROFILE_VIEWS: $PROFILE_VIEWS" # Debug step
          sed -i.bak "s/{{ dynamic_count }}/$PROFILE_VIEWS/g" README.md && rm README.md.bak
          echo "Last updated: $(date)" >> README.md # Force an update

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name 'GitHub Actions'
          git config --local user.email 'actions@github.com'
          git add README.md
          git diff --cached --exit-code || git commit -m "Update profile views to $PROFILE_VIEWS"
          git push || echo "No changes to push"
